### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [rickypeng99/maplejuice#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. It seems like a great project to learn from. Thank you.

**Comment by rickypeng99** [comment]
You can use it freely except for redistribution and usage as a project at your college (as this is a college project)

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to upload a formal license (e.g. MIT, GPL, BSD, whatever you prefer) to this repo. ? I ask just to be sure about how to treat it. In my case I am a hobbyist programmer (no school project). Thank you.
